/**
 * I2C library
 * author: Guillaume Patrigeon -- autogenerated
 * update: 08-01-2019
 */

#include "system.h"


//--------------------------------------------------------
#if defined(I2C1) && defined(_USE_I2C1)
#pragma message("Compiling functions for I2C1")


void I2C1_Init(unsigned int baudrate)
{
	I2C1.PE = 0;

	I2C1.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);
}


int I2C1_Write(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C1.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C1.SSTART = 1;
	I2C1.NACKR = 0;
	I2C1.DATA = address & 0xFE;

	while (size-- && !I2C1.NACKR)
	{
		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C1.TXBE)
			if (!I2C1.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		I2C1.DATA = *(data++);
	}

	I2C1.SSTOP = 1;

	return 0;
}


int I2C1_Read(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C1.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C1.SSTART = 1;
	I2C1.DATA = address | 1;

	while (size--)
	{
		I2C1.NACK = !size;

		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C1.RXBF)
			if (!I2C1.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		*(data++) = I2C1.DATA;
	}

	I2C1.SSTOP = 1;

	return 0;
}

#endif



//--------------------------------------------------------
#if defined(I2C2) && defined(_USE_I2C2)
#pragma message("Compiling functions for I2C2")


void I2C2_Init(unsigned int baudrate)
{
	I2C1.PE = 0;

	I2C1.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);
}


int I2C2_Write(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C2.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C2.SSTART = 1;
	I2C2.NACKR = 0;
	I2C2.DATA = address & 0xFE;

	while (size-- && !I2C2.NACKR)
	{
		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C2.TXBE)
			if (!I2C2.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		I2C2.DATA = *(data++);
	}

	I2C2.SSTOP = 1;

	return 0;
}


int I2C2_Read(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C2.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C2.SSTART = 1;
	I2C2.DATA = address | 1;

	while (size--)
	{
		I2C2.NACK = !size;

		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C2.RXBF)
			if (!I2C2.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		*(data++) = I2C2.DATA;
	}

	I2C2.SSTOP = 1;

	return 0;
}

#endif



//--------------------------------------------------------
#if defined(I2C3) && defined(_USE_I2C3)
#pragma message("Compiling functions for I2C3")


void I2C3_Init(unsigned int baudrate)
{
	I2C1.PE = 0;

	I2C1.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);
}


int I2C3_Write(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C3.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C3.SSTART = 1;
	I2C3.NACKR = 0;
	I2C3.DATA = address & 0xFE;

	while (size-- && !I2C3.NACKR)
	{
		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C3.TXBE)
			if (!I2C3.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		I2C3.DATA = *(data++);
	}

	I2C3.SSTOP = 1;

	return 0;
}


int I2C3_Read(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C3.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C3.SSTART = 1;
	I2C3.DATA = address | 1;

	while (size--)
	{
		I2C3.NACK = !size;

		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C3.RXBF)
			if (!I2C3.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		*(data++) = I2C3.DATA;
	}

	I2C3.SSTOP = 1;

	return 0;
}

#endif



//--------------------------------------------------------
#if defined(I2C4) && defined(_USE_I2C4)
#pragma message("Compiling functions for I2C4")


void I2C4_Init(unsigned int baudrate)
{
	I2C1.PE = 0;

	I2C1.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);
}


int I2C4_Write(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C4.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C4.SSTART = 1;
	I2C4.NACKR = 0;
	I2C4.DATA = address & 0xFE;

	while (size-- && !I2C4.NACKR)
	{
		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C4.TXBE)
			if (!I2C4.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		I2C4.DATA = *(data++);
	}

	I2C4.SSTOP = 1;

	return 0;
}


int I2C4_Read(unsigned char address, int size, unsigned char* data)
{
	// MONITOR.CR = MONITOR_CR_STOP;
	while (I2C4.BUSY);
	// MONITOR.CR = MONITOR_CR_START;

	I2C4.SSTART = 1;
	I2C4.DATA = address | 1;

	while (size--)
	{
		I2C4.NACK = !size;

		// MONITOR.CR = MONITOR_CR_STOP;
		while (!I2C4.RXBF)
			if (!I2C4.BUSY)
				return -1;
		// MONITOR.CR = MONITOR_CR_START;

		*(data++) = I2C4.DATA;
	}

	I2C4.SSTOP = 1;

	return 0;
}

#endif



