/**
 * SPI library
 * author: Guillaume Patrigeon -- autogenerated
 * update: 08-01-2019
 */

#ifndef __SPI_H__
#define	__SPI_H__


//--------------------------------------------------------
#if defined(SPI1) && defined(_USE_SPI1)

/// Initialize SPI1 module
void SPI1_Init(void);

/// Enable SPI1 module
#define SPI1_Enable()           SPI1.PE = 1

/// Disable SPI1 module
#define SPI1_Disable()          SPI1.PE = 0

/// Transfer data throught SPI1 module
void SPI1_Transmit(int size, const unsigned char* txbuffer, const unsigned char* rxbuffer);

#endif



//--------------------------------------------------------
#if defined(SPI2) && defined(_USE_SPI2)

/// Initialize SPI2 module
void SPI2_Init(void);

/// Enable SPI2 module
#define SPI2_Enable()           SPI2.PE = 1

/// Disable SPI2 module
#define SPI2_Disable()          SPI2.PE = 0

/// Transfer data throught SPI2 module
void SPI2_Transmit(int size, const unsigned char* txbuffer, const unsigned char* rxbuffer);

#endif



//--------------------------------------------------------
#if defined(SPI3) && defined(_USE_SPI3)

/// Initialize SPI3 module
void SPI3_Init(void);

/// Enable SPI3 module
#define SPI3_Enable()           SPI3.PE = 1

/// Disable SPI3 module
#define SPI3_Disable()          SPI3.PE = 0

/// Transfer data throught SPI3 module
void SPI3_Transmit(int size, const unsigned char* txbuffer, const unsigned char* rxbuffer);

#endif



//--------------------------------------------------------
#if defined(SPI4) && defined(_USE_SPI4)

/// Initialize SPI4 module
void SPI4_Init(void);

/// Enable SPI4 module
#define SPI4_Enable()           SPI4.PE = 1

/// Disable SPI4 module
#define SPI4_Disable()          SPI4.PE = 0

/// Transfer data throught SPI4 module
void SPI4_Transmit(int size, const unsigned char* txbuffer, const unsigned char* rxbuffer);

#endif



#endif
