#include <agspCounter.h>
#include <agspMain.h>
#include <BLE.h>
#include <timer.h>
#include "system.h"
#include "GPS.h"
#include "LoRa.h"
#include "SPI.h"
#include "OLED.h"
#include "ALS.h"
#include "TMP2.h"

void ClockInit(void);
void IO_Init(void);

void SystemInit(void)
{
	IO_Init();

	ClockInit();

#ifdef _USE_UART1
	UART1_Init();
	UART1_SetBaudrate(115200);
	UART1_Enable();
	NVIC_SET_ENABLE(NVIC_UART1);
#endif
#ifdef _USE_UART2
	UART2_Init();
	UART2_SetBaudrate(9600);
	UART2_Enable();
	NVIC_SET_ENABLE(NVIC_UART2);
#endif
#ifdef _USE_UART3
	UART3_Init();
	UART3_SetBaudrate(115200);
	UART3_Enable();
	NVIC_SET_ENABLE(NVIC_UART3);
#endif
#ifdef _USE_UART4
	UART4_Init();
	UART4_SetBaudrate(9600);
	UART4_Enable();
	NVIC_SET_ENABLE(NVIC_UART4);
#endif
#ifdef _USE_SPI1
	SPI1_Init();
	//SPI1.CLKDIV =
	SPI1_Enable();
	// NVIC_SET_ENABLE(NVIC_SPI1);
#endif
#ifdef _USE_SPI2
	SPI2_Init();
	//SPI2.CLKDIV =
	SPI2_Enable();
	// NVIC_SET_ENABLE(NVIC_SPI2);
#endif
#ifdef _USE_SPI3
	SPI3_Init();
	//SPI3.CLKDIV =
	SPI3_Enable();
	// NVIC_SET_ENABLE(NVIC_SPI3);
#endif
#ifdef _USE_SPI4
	SPI4_Init();
	//SPI4.CLKDIV =
	SPI4_Enable();
	// NVIC_SET_ENABLE(NVIC_SPI4);
#endif

#ifdef _USE_I2C1
	I2C1_Init(400000);
	I2C1_Enable();
#endif
#ifdef _USE_I2C2
	I2C2_Init(400000);
	I2C2_Enable();
#endif
	#ifdef _USE_I2C3
	I2C3_Init(400000);
	I2C3_Enable();
#endif
	#ifdef _USE_I2C4
	I2C4_Init(400000);
	I2C4_Enable();
#endif
	_INTERRUPTS_ENABLE();
}


void IO_Init(void)
{
	GPIOA.ODRbits.P3 = GPIOA.ODRbits.P4 = GPIOA.ODRbits.P5 = 1;

	GPIOA.MODEbits.P1 = GPIO_MODE_OUTPUT;
	GPIOA.MODEbits.P2 = GPIO_MODE_OUTPUT;

	//GPIOD.MODEbits.P15 = GPIO_MODE_INPUT;
	GPIOD.MODEbits.P13 = GPIO_MODE_OUTPUT; //RX
	GPIOD.MODEbits.P14 = GPIO_MODE_OUTPUT; //TX
	GPIOB.MODEbits.P0 = GPIO_MODE_OUTPUT; //RESET
	GPIOB.MODEbits.P2 = GPIO_MODE_OUTPUT; //NSELECT

	/*
	//PMODBASDROITEOLED
	GPIOD.MODEbits.P1 = GPIO_MODE_OUTPUT; //RESET
	GPIOD.MODEbits.P0 = GPIO_MODE_OUTPUT; //DATACMD
	GPIOC.MODEbits.P13 = GPIO_MODE_OUTPUT; //NSELECT
	GPIOD.MODEbits.P2 = GPIO_MODE_OUTPUT; //VBATC
	GPIOD.MODEbits.P3 = GPIO_MODE_OUTPUT; //VDDC
	 */

	//PMODHAUTGAUCHEALS
	GPIOB.MODEbits.P8 = GPIO_MODE_OUTPUT; //NSELECT

	//PMODBASDROITEBLE
	GPIOD.MODEbits.P1 = GPIO_MODE_OUTPUT; //RESET

	//UART1
#ifdef _USE_UART1
	PPSOUT.PORTA[6] = PPSOUT_UART1_TXD;
	PPSIN[PPSIN_UART1_RXD].PORT = PPS_PORTA;
	PPSIN[PPSIN_UART1_RXD].PIN = 7;
#endif

	//UART2
#ifdef _USE_UART2
	PPSOUT.PORTD[6] = PPSOUT_UART2_TXD;
	PPSIN[PPSIN_UART2_RXD].PORT = PPS_PORTD;
	PPSIN[PPSIN_UART2_RXD].PIN = 5;
#endif

	//UART3
#ifdef _USE_UART3
	PPSOUT.PORTC[12] = PPSOUT_UART3_TXD;
	PPSIN[PPSIN_UART3_RXD].PORT = PPS_PORTC;
	PPSIN[PPSIN_UART3_RXD].PIN = 11;
#endif

	// I2C1
#ifdef _USE_I2C1
	PPSOUT.PORTC[0] = PPSOUT_I2C1_SCL;
	PPSOUT.PORTB[13] = PPSOUT_I2C1_SDA;
	PPSIN[PPSIN_I2C1_SCL].PORT = PPS_PORTC;
	PPSIN[PPSIN_I2C1_SCL].PIN = 0;
	PPSIN[PPSIN_I2C1_SDA].PORT = PPS_PORTB;
	PPSIN[PPSIN_I2C1_SDA].PIN = 13;
#endif

	// I2C2
#ifdef _USE_I2C2
	PPSOUT.PORTC[0] = PPSOUT_I2C2_SCL;
	PPSOUT.PORTB[13] = PPSOUT_I2C2_SDA;
	PPSIN[PPSIN_I2C2_SCL].PORT = PPS_PORTC;
	PPSIN[PPSIN_I2C2_SCL].PIN = 0;
	PPSIN[PPSIN_I2C2_SDA].PORT = PPS_PORTB;
	PPSIN[PPSIN_I2C2_SDA].PIN = 13;
#endif

	//PMODHAUTLORA
	PPSOUT.PORTB[1] = PPSOUT_SPI1_SCK;
	PPSOUT.PORTB[3] = PPSOUT_SPI1_SDO;
	PPSIN[PPSIN_SPI1_SDI].PORT = PPS_PORTB;
	PPSIN[PPSIN_SPI1_SDI].PIN = 4;

	/*
	//PMODBASDROITEOLED
	PPSOUT.PORTC[10] = PPSOUT_SPI2_SCK;
	PPSOUT.PORTC[12] = PPSOUT_SPI2_SDO;
	PPSIN[PPSIN_SPI2_SDI].PORT = PPS_PORTC;
	PPSIN[PPSIN_SPI2_SDI].PIN = 11;
	*/

	//PMODHAUTGAUCHEALS
	PPSOUT.PORTB[5] = PPSOUT_SPI2_SCK;
	PPSOUT.PORTB[7] = PPSOUT_SPI2_SDO;
	PPSIN[PPSIN_SPI2_SDI].PORT = PPS_PORTB;
	PPSIN[PPSIN_SPI2_SDI].PIN = 6;
}


