/**
 * UART library
 * author: Guillaume Patrigeon -- autogenerated
 * update: 08-01-2019
 */

#include "system.h"


//--------------------------------------------------------
#if defined(UART1) && defined(_USE_UART1)
#pragma message("Compiling functions for UART1")

static volatile char UART1_TxBuffer[UART1_TXBUFFERSIZE];
static volatile int UART1_TxFirst, UART1_TxLast, UART1_TxCount;

static volatile char UART1_RxBuffer[UART1_RXBUFFERSIZE];
static volatile int UART1_RxFirst, UART1_RxLast, UART1_RxCount;


void UART1_Init(void)
{
	UART1.PE = 0;

	UART1_TxFirst = UART1_TxLast = UART1_TxCount = 0;
	UART1_RxFirst = UART1_RxLast = UART1_RxCount = 0;

	UART1.RXBFIE = 1;
}


void UART1_SetBaudrate(unsigned int baudrate)
{
	unsigned int en;

	en = UART1.PE;

	UART1.PE = 0;
	UART1.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);

	UART1.PE = en;
}


void UART1_Send(const char c)
{
	if (UART1_TxCount >= UART1_TXBUFFERSIZE - 1)
		return;

	UART1.TXBEIE = 0;

	UART1_TxBuffer[UART1_TxFirst++] = c;
	UART1_TxCount++;

	if (UART1_TxFirst >= UART1_TXBUFFERSIZE)
		UART1_TxFirst = 0;

	UART1.TXBEIE = 1;
}


int UART1_IsRxNotEmpty(void)
{
	return (UART1_RxFirst != UART1_RxLast);
}


char UART1_Read(void)
{
	char c;

	if (UART1_RxFirst == UART1_RxLast)
	{
		UART1_RxCount = 0;
		return 0;
	}

	c = UART1_RxBuffer[UART1_RxLast++];
	UART1_RxCount--;

	if (UART1_RxLast >= UART1_RXBUFFERSIZE)
		UART1_RxLast = 0;

	return c;
}


void UART1_Clean(void)
{
	UART1.TXBEIE = 0;
	UART1.RXBFIE = 0;

	UART1_TxFirst = UART1_TxLast = UART1_TxCount = 0;
	UART1_RxFirst = UART1_RxLast = UART1_RxCount = 0;

	UART1.RXBFIE = 1;
}


int UART1_GetRxCount(void)
{
	return UART1_RxCount;
}


int UART1_GetTxCount(void)
{
	return UART1_TxCount;
}


void UART1_IRQHandler(void)
{
	if (UART1.TXBEIE && UART1.TXBE)
	{
		if (UART1_TxFirst == UART1_TxLast)
		{
			UART1_TxCount = 0;
			UART1.TXBEIE = 0;
		}
		else
		{
			UART1.DATA = UART1_TxBuffer[UART1_TxLast++];
			UART1_TxCount--;

			if (UART1_TxLast >= UART1_TXBUFFERSIZE)
				UART1_TxLast = 0;
		}
	}

	if (UART1.RXBFIE && UART1.RXBF)
	{
		UART1_RxBuffer[UART1_RxFirst] = UART1.DATA;

		if (UART1_RxCount < UART1_RXBUFFERSIZE - 1)
		{
			UART1_RxFirst++;
			UART1_RxCount++;

			if (UART1_RxFirst >= UART1_RXBUFFERSIZE)
				UART1_RxFirst = 0;
		}
	}
}

#endif



//--------------------------------------------------------
#if defined(UART2) && defined(_USE_UART2)
#pragma message("Compiling functions for UART2")

static volatile char UART2_TxBuffer[UART2_TXBUFFERSIZE];
static volatile int UART2_TxFirst, UART2_TxLast, UART2_TxCount;

static volatile char UART2_RxBuffer[UART2_RXBUFFERSIZE];
static volatile int UART2_RxFirst, UART2_RxLast, UART2_RxCount;


void UART2_Init(void)
{
	UART2.PE = 0;

	UART2_TxFirst = UART2_TxLast = UART2_TxCount = 0;
	UART2_RxFirst = UART2_RxLast = UART2_RxCount = 0;

	UART2.RXBFIE = 1;
}


void UART2_SetBaudrate(unsigned int baudrate)
{
	unsigned int en;

	en = UART2.PE;

	UART2.PE = 0;
	UART2.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);

	UART2.PE = en;
}


void UART2_Send(const char c)
{
	if (UART2_TxCount >= UART2_TXBUFFERSIZE - 1)
		return;

	UART2.TXBEIE = 0;

	UART2_TxBuffer[UART2_TxFirst++] = c;
	UART2_TxCount++;

	if (UART2_TxFirst >= UART2_TXBUFFERSIZE)
		UART2_TxFirst = 0;

	UART2.TXBEIE = 1;
}


int UART2_IsRxNotEmpty(void)
{
	return (UART2_RxFirst != UART2_RxLast);
}


char UART2_Read(void)
{
	char c;

	if (UART2_RxFirst == UART2_RxLast)
	{
		UART2_RxCount = 0;
		return 0;
	}

	c = UART2_RxBuffer[UART2_RxLast++];
	UART2_RxCount--;

	if (UART2_RxLast >= UART2_RXBUFFERSIZE)
		UART2_RxLast = 0;

	return c;
}


void UART2_Clean(void)
{
	UART2.TXBEIE = 0;
	UART2.RXBFIE = 0;

	UART2_TxFirst = UART2_TxLast = UART2_TxCount = 0;
	UART2_RxFirst = UART2_RxLast = UART2_RxCount = 0;

	UART2.RXBFIE = 1;
}


int UART2_GetRxCount(void)
{
	return UART2_RxCount;
}


int UART2_GetTxCount(void)
{
	return UART2_TxCount;
}


void UART2_IRQHandler(void)
{
	if (UART2.TXBEIE && UART2.TXBE)
	{
		if (UART2_TxFirst == UART2_TxLast)
		{
			UART2_TxCount = 0;
			UART2.TXBEIE = 0;
		}
		else
		{
			UART2.DATA = UART2_TxBuffer[UART2_TxLast++];
			UART2_TxCount--;

			if (UART2_TxLast >= UART2_TXBUFFERSIZE)
				UART2_TxLast = 0;
		}
	}

	if (UART2.RXBFIE && UART2.RXBF)
	{
		UART2_RxBuffer[UART2_RxFirst] = UART2.DATA;

		if (UART2_RxCount < UART2_RXBUFFERSIZE - 1)
		{
			UART2_RxFirst++;
			UART2_RxCount++;

			if (UART2_RxFirst >= UART2_RXBUFFERSIZE)
				UART2_RxFirst = 0;
		}
	}
}

#endif



//--------------------------------------------------------
#if defined(UART3) && defined(_USE_UART3)
#pragma message("Compiling functions for UART3")

static volatile char UART3_TxBuffer[UART3_TXBUFFERSIZE];
static volatile int UART3_TxFirst, UART3_TxLast, UART3_TxCount;

static volatile char UART3_RxBuffer[UART3_RXBUFFERSIZE];
static volatile int UART3_RxFirst, UART3_RxLast, UART3_RxCount;


void UART3_Init(void)
{
	UART3.PE = 0;

	UART3_TxFirst = UART3_TxLast = UART3_TxCount = 0;
	UART3_RxFirst = UART3_RxLast = UART3_RxCount = 0;

	UART3.RXBFIE = 1;
}


void UART3_SetBaudrate(unsigned int baudrate)
{
	unsigned int en;

	en = UART3.PE;

	UART3.PE = 0;
	UART3.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);

	UART3.PE = en;
}


void UART3_Send(const char c)
{
	if (UART3_TxCount >= UART3_TXBUFFERSIZE - 1)
		return;

	UART3.TXBEIE = 0;

	UART3_TxBuffer[UART3_TxFirst++] = c;
	UART3_TxCount++;

	if (UART3_TxFirst >= UART3_TXBUFFERSIZE)
		UART3_TxFirst = 0;

	UART3.TXBEIE = 1;
}


int UART3_IsRxNotEmpty(void)
{
	return (UART3_RxFirst != UART3_RxLast);
}


char UART3_Read(void)
{
	char c;

	if (UART3_RxFirst == UART3_RxLast)
	{
		UART3_RxCount = 0;
		return 0;
	}

	c = UART3_RxBuffer[UART3_RxLast++];
	UART3_RxCount--;

	if (UART3_RxLast >= UART3_RXBUFFERSIZE)
		UART3_RxLast = 0;

	return c;
}


void UART3_Clean(void)
{
	UART3.TXBEIE = 0;
	UART3.RXBFIE = 0;

	UART3_TxFirst = UART3_TxLast = UART3_TxCount = 0;
	UART3_RxFirst = UART3_RxLast = UART3_RxCount = 0;

	UART3.RXBFIE = 1;
}


int UART3_GetRxCount(void)
{
	return UART3_RxCount;
}


int UART3_GetTxCount(void)
{
	return UART3_TxCount;
}


void UART3_IRQHandler(void)
{
	if (UART3.TXBEIE && UART3.TXBE)
	{
		if (UART3_TxFirst == UART3_TxLast)
		{
			UART3_TxCount = 0;
			UART3.TXBEIE = 0;
		}
		else
		{
			UART3.DATA = UART3_TxBuffer[UART3_TxLast++];
			UART3_TxCount--;

			if (UART3_TxLast >= UART3_TXBUFFERSIZE)
				UART3_TxLast = 0;
		}
	}

	if (UART3.RXBFIE && UART3.RXBF)
	{
		UART3_RxBuffer[UART3_RxFirst] = UART3.DATA;

		if (UART3_RxCount < UART3_RXBUFFERSIZE - 1)
		{
			UART3_RxFirst++;
			UART3_RxCount++;

			if (UART3_RxFirst >= UART3_RXBUFFERSIZE)
				UART3_RxFirst = 0;
		}
	}
}

#endif



//--------------------------------------------------------
#if defined(UART4) && defined(_USE_UART4)
#pragma message("Compiling functions for UART4")

static volatile char UART4_TxBuffer[UART4_TXBUFFERSIZE];
static volatile int UART4_TxFirst, UART4_TxLast, UART4_TxCount;

static volatile char UART4_RxBuffer[UART4_RXBUFFERSIZE];
static volatile int UART4_RxFirst, UART4_RxLast, UART4_RxCount;


void UART4_Init(void)
{
	UART4.PE = 0;

	UART4_TxFirst = UART4_TxLast = UART4_TxCount = 0;
	UART4_RxFirst = UART4_RxLast = UART4_RxCount = 0;

	UART4.RXBFIE = 1;
}


void UART4_SetBaudrate(unsigned int baudrate)
{
	unsigned int en;

	en = UART4.PE;

	UART4.PE = 0;
	UART4.CLKDIV = (SYSCLK - 2*baudrate)/(4*baudrate);

	UART4.PE = en;
}


void UART4_Send(const char c)
{
	if (UART4_TxCount >= UART4_TXBUFFERSIZE - 1)
		return;

	UART4.TXBEIE = 0;

	UART4_TxBuffer[UART4_TxFirst++] = c;
	UART4_TxCount++;

	if (UART4_TxFirst >= UART4_TXBUFFERSIZE)
		UART4_TxFirst = 0;

	UART4.TXBEIE = 1;
}


int UART4_IsRxNotEmpty(void)
{
	return (UART4_RxFirst != UART4_RxLast);
}


char UART4_Read(void)
{
	char c;

	if (UART4_RxFirst == UART4_RxLast)
	{
		UART4_RxCount = 0;
		return 0;
	}

	c = UART4_RxBuffer[UART4_RxLast++];
	UART4_RxCount--;

	if (UART4_RxLast >= UART4_RXBUFFERSIZE)
		UART4_RxLast = 0;

	return c;
}


void UART4_Clean(void)
{
	UART4.TXBEIE = 0;
	UART4.RXBFIE = 0;

	UART4_TxFirst = UART4_TxLast = UART4_TxCount = 0;
	UART4_RxFirst = UART4_RxLast = UART4_RxCount = 0;

	UART4.RXBFIE = 1;
}


int UART4_GetRxCount(void)
{
	return UART4_RxCount;
}


int UART4_GetTxCount(void)
{
	return UART4_TxCount;
}


void UART4_IRQHandler(void)
{
	if (UART4.TXBEIE && UART4.TXBE)
	{
		if (UART4_TxFirst == UART4_TxLast)
		{
			UART4_TxCount = 0;
			UART4.TXBEIE = 0;
		}
		else
		{
			UART4.DATA = UART4_TxBuffer[UART4_TxLast++];
			UART4_TxCount--;

			if (UART4_TxLast >= UART4_TXBUFFERSIZE)
				UART4_TxLast = 0;
		}
	}

	if (UART4.RXBFIE && UART4.RXBF)
	{
		UART4_RxBuffer[UART4_RxFirst] = UART4.DATA;

		if (UART4_RxCount < UART4_RXBUFFERSIZE - 1)
		{
			UART4_RxFirst++;
			UART4_RxCount++;

			if (UART4_RxFirst >= UART4_RXBUFFERSIZE)
				UART4_RxFirst = 0;
		}
	}
}

#endif



